Session and filter are implemented
andromash/jv-internet-shop-romash pull request #6
Opened 2020-09-14 16:32 UTC by andromash

2020-09-14 16:36 UTC, DariaPikul requested changes

2020-09-14 16:36 UTC, DariaPikul commented on src/main/java/com/internet/shop/security/AuthenticationServiceImpl.java
> +                new AuthenticationException("Incorrect name or password"));
```suggestion
                new AuthenticationException("Incorrect login or password"));
```

2020-09-14 16:36 UTC, DariaPikul commented on src/main/java/com/internet/shop/web/filter/AuthenticationFilter.java
> +        if (userId == null || userService.get(userId) == null) {
```suggestion
        if (userId == null) {
```

2020-09-14 16:43 UTC, DariaPikul approved these changes

2020-09-14 19:34 UTC, DariaPikul approved these changes

2020-09-15 08:28 UTC, KseniiaMakarova approved these changes

2020-09-15 08:28 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/LoginController.java
> +            httpSession.setAttribute("user_id", user.getId());
let's make `user_id` constant

2020-09-15 08:28 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/UserDaoImpl.java
> +                .filter(s -> s.getLogin().equals(login))
`s` is not informative

2020-09-15 10:12 UTC, merged