Hw 29
andromash/jv-internet-shop-romash pull request #8
Opened 2020-09-16 09:50 UTC by andromash

2020-09-16 10:03 UTC, AndrewPolishchuc approved these changes
Great job!

2020-09-16 16:23 UTC, KseniiaMakarova requested changes
can you guarantee the order in which your filters execute? let's indicate order in web.xml

2020-09-16 16:23 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/user/RegistrationController.java
> +            }
I would recommend to set only USER role to everyone who registers

and inject Admin in InjectController 
admin should not have his own shopping cart

2020-09-16 16:23 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/web/filter/AuthenticationFilter.java
> +        Long userId = (Long) req.getSession().getAttribute(LoginController.USER_ID);
let's also refactor AuthenticationFilter as proposed in the checklist

2020-09-16 16:23 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/web/filter/AuthorizationFilter.java
> +        if (!protectedUrls.containsKey(url)) {
let's put both conditions in one `if`

2020-09-16 16:23 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/web/filter/AuthorizationFilter.java
> +        protectedUrls.put("/orders/all", List.of(Role.RoleName.ADMIN));
what about DeleteOrderController?

2020-09-16 16:23 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/web/filter/AuthorizationFilter.java
> +        protectedUrls.put("/shopping-cart/product/delete", List.of(Role.RoleName.USER));
and AddToCartController

2020-09-16 16:25 UTC, andromash commented on src/main/java/com/internet/shop/controllers/user/RegistrationController.java
> +            }
This was necessary because I do not have InjectController

2020-09-16 16:32 UTC, andromash commented on src/main/java/com/internet/shop/web/filter/AuthenticationFilter.java
> +        Long userId = (Long) req.getSession().getAttribute(LoginController.USER_ID);
agree

2020-09-16 16:33 UTC, andromash commented on src/main/java/com/internet/shop/web/filter/AuthorizationFilter.java
> +        protectedUrls.put("/shopping-cart/product/delete", List.of(Role.RoleName.USER));
addToCart has url /product/buy

2020-09-16 16:35 UTC, andromash commented on src/main/java/com/internet/shop/controllers/user/RegistrationController.java
> +            }
As we will connect the real database I will remove it
About shopping cart - agree.

2020-09-16 16:45 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/user/RegistrationController.java
> +            }
I think it is better to create InjectAdminController then to write complex logic here

2020-09-17 07:59 UTC, KseniiaMakarova requested changes

2020-09-17 07:59 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/LoginController.java
> +        }
let's better not change this and inject admin with some button

2020-09-17 09:41 UTC, KseniiaMakarova approved these changes

2020-09-17 11:12 UTC, merged